name: Development

on: 
  push:
    branches:
      - "development"
  pull_request:
    branches:
      - "development"

jobs:
  testing:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup Project
        run: |
          php artisan key:generate
          php artisan jwt:secret
          php artisan config:clear
          php artisan cache:clear
      - name: Directory Permissions
        run: chmod 777 -R storage bootstrap/cache
      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run Unit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          APP_ENV: testing
        run: vendor/bin/phpunit
